categories = ["Added", "Changed", "Fixed", "Improved", "Removed"]
colored_output = true
enable_debug = true
enable_footers = false
excluded_commit_tags = []
show_prefix = false
template_prefix = "JIRA-1234"
